export type PageNamingSignals = {
  url: string;
  title?: string;
  headers: string[];
  purposeHint?: string;
};

export async function aiNamePage(signals: PageNamingSignals): Promise<string> {
  // Uses OpenAI if OPENAI_API_KEY is present; otherwise falls back to heuristics.
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return heuristicPageName(signals);

  try {
    const prompt = `You are a QA automation framework architect. Given signals from a web page, produce a concise Playwright Page Object class name in PascalCase and ending with 'Page'.\n\nRules:\n- Output ONLY the class name.\n- Use intent/purpose, not company/product names.\n- Examples: LoginPage, DashboardPage, UserManagementPage, SearchResultsPage, SettingsPage.\n\nSignals:\nURL: ${signals.url}\nTitle: ${signals.title ?? ''}\nH1/H2: ${signals.headers.slice(0, 6).join(' | ')}\nHint: ${signals.purposeHint ?? ''}\n`;

    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL ?? 'gpt-4o-mini',
        messages: [
          { role: 'system', content: 'You output only the requested class name.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.2,
      }),
    });

    if (!res.ok) return heuristicPageName(signals);
    const json: any = await res.json();
    const text = String(json?.choices?.[0]?.message?.content ?? '').trim();
    const cleaned = text.replace(/[^A-Za-z0-9]/g, '');
    if (!cleaned) return heuristicPageName(signals);
    return cleaned.endsWith('Page') ? cleaned : `${cleaned}Page`;
  } catch {
    return heuristicPageName(signals);
  }
}

export function heuristicPageName(signals: PageNamingSignals): string {
  const candidates = [
    ...(signals.headers ?? []),
    signals.title ?? '',
    new URL(signals.url).pathname.split('/').filter(Boolean).slice(-2).join(' '),
  ]
    .join(' ')
    .toLowerCase();

  const map: Array<[RegExp, string]> = [
    [/login|sign in|signin|log in/, 'LoginPage'],
    [/dashboard|home/, 'DashboardPage'],
    [/users|user management|manage users/, 'UserManagementPage'],
    [/settings|preferences/, 'SettingsPage'],
    [/search|results/, 'SearchResultsPage'],
    [/checkout/, 'CheckoutPage'],
  ];

  for (const [re, name] of map) {
    if (re.test(candidates)) return name;
  }

  const base = (signals.headers?.[0] || signals.title || 'AutoGenerated')
    .replace(/[^a-zA-Z0-9 ]/g, ' ')
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');

  const safe = base || 'AutoGenerated';
  return safe.endsWith('Page') ? safe : `${safe}Page`;
}
